language: minimal
services:
  - docker

install:
  - docker build -t land-registry-elements .
  - docker run -itd --name land-registry-elements land-registry-elements bash
  - docker cp . land-registry-elements:/src/.
  - docker exec land-registry-elements npm run build
  - docker exec -d land-registry-elements /usr/bin/gunicorn -k eventlet --pythonpath /src --access-logfile - manage:manager.app --reload

script:
  - docker exec land-registry-elements npm run test
