sudo: required
dist: trusty
language: node_js

node_js:
  - "6"

python:
  - "3.4"

before_install:
  - hash -r
  - rvm install 2.4.1
  - sudo apt-get -y install python3-pip python-dev

cache:
  directories:
    - node_modules

install:
  - bundle install
  - npm install
  - pip3 install -r demo/requirements.txt

before_script:
  - npm run build
  - make & # Run the python demo server in the background
