language: node_js
node_js:
  - "6"
before_install:
  - npm install -g mocha
  - npm install -g eslint

before_deploy:
  - tar cvzf test/fixtures/visual-regression/test-renderings.tar.gz test/fixtures/visual-regression/test-renderings

cache:
  directories:
    - node_modules

addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - test/fixtures/visual-regression
