language: node_js
node_js:
  - "5"
before_install:
  - npm install -g mocha
  - npm install -g eslint
  - npm install -g eslint-plugin-cross-browser-compatibility-check

cache:
  directories:
    - node_modules

addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - test/fixtures/visual-regression
  apt:
    packages:
    - graphicsmagick
