language: node_js

node_js:
  - "6"

python:
  - "3.4"

before_install:
  - sudo apt-get install curl -qq
  - rvm install 2.4.1

cache:
  directories:
    - node_modules

install:
  - bundle install
  - npm install
  - pip3 install -r requirements.txt

before_script:
  - make  # Run the python demo server
