require('./javascript/html5shiv');

require('./javascript/Array.isArray');
require('./javascript/Event');
require('./javascript/Array.prototype.every');
require('./javascript/Array.prototype.filter');
require('./javascript/Array.prototype.forEach');
require('./javascript/Array.prototype.indexOf');
require('./javascript/Array.prototype.map');
require('./javascript/Array.prototype.reduce');
require('./javascript/Date.now');
require('./javascript/Element.classList');
require('./javascript/Function.prototype.bind');
require('./javascript/Object.defineProperties');
require('./javascript/Object.defineProperty');
require('./javascript/Object.keys');
require('./javascript/String.prototype.trim');
require('./javascript/Window.prototype.matchMedia');
require('./javascript/Window.JSON');
